name: Windows Client (dotnet build and test)

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  os-tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version:  |
<<<<<<< HEAD
            3.1.x
            5.0.x
            6.0.x
            7.0.x
      - name: Install Android
        run: dotnet workload install android
=======
            7.0.x
>>>>>>> 47c72c418b676634e1cbb141304b4b12e6a615e0
      - name: Restore dependencies
        run: dotnet restore ./src/CSharp/EasyMicroservices.EmailsMicroservice.Client.sln
      - name: Build
        run: dotnet build ./src/CSharp/EasyMicroservices.EmailsMicroservice.Client.sln --no-restore
      - name: Test
        run: dotnet test ./src/CSharp/EasyMicroservices.EmailsMicroservice.Client.sln --no-build --verbosity normal
