name: MacOS (dotnet build and test)

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  os-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version:  |
<<<<<<< HEAD
            3.1.x
            5.0.x
            6.0.x
            7.0.x
      - name: Install Android
        run: dotnet workload install android
=======
            7.0.x
>>>>>>> 47c72c418b676634e1cbb141304b4b12e6a615e0
      - name: Restore dependencies
        run: dotnet restore ./src/CSharp/EasyMicroservices.EmailsMicroservice.sln
      - name: Build
        run: dotnet build ./src/CSharp/EasyMicroservices.EmailsMicroservice.sln --no-restore
      - name: Test
        run:  |
<<<<<<< HEAD
          dotnet test ./src/CSharp/EasyMicroservices.EmailsMicroservice.sln --no-build --verbosity normal -f netcoreapp3.1
          dotnet test ./src/CSharp/EasyMicroservices.EmailsMicroservice.sln --no-build --verbosity normal -f net6.0
          dotnet test ./src/CSharp/EasyMicroservices.EmailsMicroservice.sln --no-build --verbosity normal -f net5.0
=======
          dotnet test ./src/CSharp/EasyMicroservices.EmailsMicroservice.sln --no-build --verbosity normal -f net7.0
>>>>>>> 47c72c418b676634e1cbb141304b4b12e6a615e0
